<a href="https://colab.research.google.com/github/atirek89/ai-ml-foundations/blob/main/01_Linear_Algebra_Numpy_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Create a 2x2 matrix
A = np.array([[2, 3], [4, 5]])

# Transpose of A
print("Transpose of A:\n", A.T)

# Matrix multiplication (dot product)
B = np.array([[1, 2], [3, 4]])
print("A dot B:\n", np.dot(A, B))

# Inverse of A
A_inv = np.linalg.inv(A)
print("Inverse of A:\n", A_inv)

Transpose of A:
 [[2 4]
 [3 5]]
A dot B:
 [[11 16]
 [19 28]]
Inverse of A:
 [[-2.5  1.5]
 [ 2.  -1. ]]
